name: Build and Release Native Image

on:
  push:
    tags:
      - 'v*' # triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        version: '23.1.1'
        java-version: '21'
        components: 'native-image'

    - name: Build native image
      run: ./mvnw package -Pnative

    - name: Get artifact name
      id: get_artifact
      run: |
        ARTIFACT=$(ls target/*-runner | head -n 1)
        echo "artifact=$ARTIFACT" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.get_artifact.outputs.artifact }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
